/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUploadMarksRouteImport } from './routes/_app.upload-marks'
import { Route as AppTimetableRouteImport } from './routes/_app.timetable'
import { Route as AppSubjectsRouteImport } from './routes/_app.subjects'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppStudentPerformanceRouteImport } from './routes/_app.student-performance'
import { Route as AppResultsRouteImport } from './routes/_app.results'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMySubjectsRouteImport } from './routes/_app.my-subjects'
import { Route as AppMyResultsRouteImport } from './routes/_app.my-results'
import { Route as AppMyAttendanceRouteImport } from './routes/_app.my-attendance'
import { Route as AppMarkAttendanceRouteImport } from './routes/_app.mark-attendance'
import { Route as AppLeaveRequestsRouteImport } from './routes/_app.leave-requests'
import { Route as AppFeesRouteImport } from './routes/_app.fees'
import { Route as AppFeeStatusRouteImport } from './routes/_app.fee-status'
import { Route as AppFacultyRouteImport } from './routes/_app.faculty'
import { Route as AppDepartmentsRouteImport } from './routes/_app.departments'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCoursesRouteImport } from './routes/_app.courses'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAnnouncementsRouteImport } from './routes/_app.announcements'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadMarksRoute = AppUploadMarksRouteImport.update({
  id: '/upload-marks',
  path: '/upload-marks',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentPerformanceRoute = AppStudentPerformanceRouteImport.update({
  id: '/student-performance',
  path: '/student-performance',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMySubjectsRoute = AppMySubjectsRouteImport.update({
  id: '/my-subjects',
  path: '/my-subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppMyResultsRoute = AppMyResultsRouteImport.update({
  id: '/my-results',
  path: '/my-results',
  getParentRoute: () => AppRoute,
} as any)
const AppMyAttendanceRoute = AppMyAttendanceRouteImport.update({
  id: '/my-attendance',
  path: '/my-attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppMarkAttendanceRoute = AppMarkAttendanceRouteImport.update({
  id: '/mark-attendance',
  path: '/mark-attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRequestsRoute = AppLeaveRequestsRouteImport.update({
  id: '/leave-requests',
  path: '/leave-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppFeeStatusRoute = AppFeeStatusRouteImport.update({
  id: '/fee-status',
  path: '/fee-status',
  getParentRoute: () => AppRoute,
} as any)
const AppFacultyRoute = AppFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit': typeof AppAuditRoute
  '/courses': typeof AppCoursesRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/faculty': typeof AppFacultyRoute
  '/fee-status': typeof AppFeeStatusRoute
  '/fees': typeof AppFeesRoute
  '/leave-requests': typeof AppLeaveRequestsRoute
  '/mark-attendance': typeof AppMarkAttendanceRoute
  '/my-attendance': typeof AppMyAttendanceRoute
  '/my-results': typeof AppMyResultsRoute
  '/my-subjects': typeof AppMySubjectsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/results': typeof AppResultsRoute
  '/student-performance': typeof AppStudentPerformanceRoute
  '/students': typeof AppStudentsRoute
  '/subjects': typeof AppSubjectsRoute
  '/timetable': typeof AppTimetableRoute
  '/upload-marks': typeof AppUploadMarksRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/announcements': typeof AppAnnouncementsRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit': typeof AppAuditRoute
  '/courses': typeof AppCoursesRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/faculty': typeof AppFacultyRoute
  '/fee-status': typeof AppFeeStatusRoute
  '/fees': typeof AppFeesRoute
  '/leave-requests': typeof AppLeaveRequestsRoute
  '/mark-attendance': typeof AppMarkAttendanceRoute
  '/my-attendance': typeof AppMyAttendanceRoute
  '/my-results': typeof AppMyResultsRoute
  '/my-subjects': typeof AppMySubjectsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/results': typeof AppResultsRoute
  '/student-performance': typeof AppStudentPerformanceRoute
  '/students': typeof AppStudentsRoute
  '/subjects': typeof AppSubjectsRoute
  '/timetable': typeof AppTimetableRoute
  '/upload-marks': typeof AppUploadMarksRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/announcements': typeof AppAnnouncementsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/courses': typeof AppCoursesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/faculty': typeof AppFacultyRoute
  '/_app/fee-status': typeof AppFeeStatusRoute
  '/_app/fees': typeof AppFeesRoute
  '/_app/leave-requests': typeof AppLeaveRequestsRoute
  '/_app/mark-attendance': typeof AppMarkAttendanceRoute
  '/_app/my-attendance': typeof AppMyAttendanceRoute
  '/_app/my-results': typeof AppMyResultsRoute
  '/_app/my-subjects': typeof AppMySubjectsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/results': typeof AppResultsRoute
  '/_app/student-performance': typeof AppStudentPerformanceRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/subjects': typeof AppSubjectsRoute
  '/_app/timetable': typeof AppTimetableRoute
  '/_app/upload-marks': typeof AppUploadMarksRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/announcements'
    | '/attendance'
    | '/audit'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/faculty'
    | '/fee-status'
    | '/fees'
    | '/leave-requests'
    | '/mark-attendance'
    | '/my-attendance'
    | '/my-results'
    | '/my-subjects'
    | '/profile'
    | '/reports'
    | '/results'
    | '/student-performance'
    | '/students'
    | '/subjects'
    | '/timetable'
    | '/upload-marks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/announcements'
    | '/attendance'
    | '/audit'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/faculty'
    | '/fee-status'
    | '/fees'
    | '/leave-requests'
    | '/mark-attendance'
    | '/my-attendance'
    | '/my-results'
    | '/my-subjects'
    | '/profile'
    | '/reports'
    | '/results'
    | '/student-performance'
    | '/students'
    | '/subjects'
    | '/timetable'
    | '/upload-marks'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/announcements'
    | '/_app/attendance'
    | '/_app/audit'
    | '/_app/courses'
    | '/_app/dashboard'
    | '/_app/departments'
    | '/_app/faculty'
    | '/_app/fee-status'
    | '/_app/fees'
    | '/_app/leave-requests'
    | '/_app/mark-attendance'
    | '/_app/my-attendance'
    | '/_app/my-results'
    | '/_app/my-subjects'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/results'
    | '/_app/student-performance'
    | '/_app/students'
    | '/_app/subjects'
    | '/_app/timetable'
    | '/_app/upload-marks'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload-marks': {
      id: '/_app/upload-marks'
      path: '/upload-marks'
      fullPath: '/upload-marks'
      preLoaderRoute: typeof AppUploadMarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable': {
      id: '/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects': {
      id: '/_app/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student-performance': {
      id: '/_app/student-performance'
      path: '/student-performance'
      fullPath: '/student-performance'
      preLoaderRoute: typeof AppStudentPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results': {
      id: '/_app/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-subjects': {
      id: '/_app/my-subjects'
      path: '/my-subjects'
      fullPath: '/my-subjects'
      preLoaderRoute: typeof AppMySubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-results': {
      id: '/_app/my-results'
      path: '/my-results'
      fullPath: '/my-results'
      preLoaderRoute: typeof AppMyResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-attendance': {
      id: '/_app/my-attendance'
      path: '/my-attendance'
      fullPath: '/my-attendance'
      preLoaderRoute: typeof AppMyAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mark-attendance': {
      id: '/_app/mark-attendance'
      path: '/mark-attendance'
      fullPath: '/mark-attendance'
      preLoaderRoute: typeof AppMarkAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave-requests': {
      id: '/_app/leave-requests'
      path: '/leave-requests'
      fullPath: '/leave-requests'
      preLoaderRoute: typeof AppLeaveRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees': {
      id: '/_app/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fee-status': {
      id: '/_app/fee-status'
      path: '/fee-status'
      fullPath: '/fee-status'
      preLoaderRoute: typeof AppFeeStatusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faculty': {
      id: '/_app/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof AppFacultyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements': {
      id: '/_app/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCoursesRoute: typeof AppCoursesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppFacultyRoute: typeof AppFacultyRoute
  AppFeeStatusRoute: typeof AppFeeStatusRoute
  AppFeesRoute: typeof AppFeesRoute
  AppLeaveRequestsRoute: typeof AppLeaveRequestsRoute
  AppMarkAttendanceRoute: typeof AppMarkAttendanceRoute
  AppMyAttendanceRoute: typeof AppMyAttendanceRoute
  AppMyResultsRoute: typeof AppMyResultsRoute
  AppMySubjectsRoute: typeof AppMySubjectsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResultsRoute: typeof AppResultsRoute
  AppStudentPerformanceRoute: typeof AppStudentPerformanceRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppTimetableRoute: typeof AppTimetableRoute
  AppUploadMarksRoute: typeof AppUploadMarksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppAuditRoute: AppAuditRoute,
  AppCoursesRoute: AppCoursesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppFacultyRoute: AppFacultyRoute,
  AppFeeStatusRoute: AppFeeStatusRoute,
  AppFeesRoute: AppFeesRoute,
  AppLeaveRequestsRoute: AppLeaveRequestsRoute,
  AppMarkAttendanceRoute: AppMarkAttendanceRoute,
  AppMyAttendanceRoute: AppMyAttendanceRoute,
  AppMyResultsRoute: AppMyResultsRoute,
  AppMySubjectsRoute: AppMySubjectsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppResultsRoute: AppResultsRoute,
  AppStudentPerformanceRoute: AppStudentPerformanceRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppTimetableRoute: AppTimetableRoute,
  AppUploadMarksRoute: AppUploadMarksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
